///////////////////////////////////////////////////////////////////////////////
//   ____  ____ 
//  /   /\/   /
// /___/  \  /    Vendor: Xilinx
// \   \   \/     Version : 2.5
//  \   \         Application : 7 Series FPGAs Transceivers Wizard
//  /   /         Filename : system_displayport_0_0_gt_7_series_wrapper_4.v
// /___/   /\     
// \   \  /  \ 
//  \___\/\___\
//
//
// Module system_displayport_0_0_gt_7_series_wrapper_4 (a GT Wrapper)
// Generated by Xilinx 7 Series FPGAs Transceivers Wizard
// 
// 
// (c) Copyright 2010-2012 Xilinx, Inc. All rights reserved.
// 
// This file contains confidential and proprietary information
// of Xilinx, Inc. and is protected under U.S. and
// international copyright and other intellectual property
// laws.
// 
// DISCLAIMER
// This disclaimer is not a license and does not grant any
// rights to the materials distributed herewith. Except as
// otherwise provided in a valid license issued to you by
// Xilinx, and to the maximum extent permitted by applicable
// law: (1) THESE MATERIALS ARE MADE AVAILABLE "AS IS" AND
// WITH ALL FAULTS, AND XILINX HEREBY DISCLAIMS ALL WARRANTIES
// AND CONDITIONS, EXPRESS, IMPLIED, OR STATUTORY, INCLUDING
// BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, NON-
// INFRINGEMENT, OR FITNESS FOR ANY PARTICULAR PURPOSE; and
// (2) Xilinx shall not be liable (whether in contract or tort,
// including negligence, or under any other theory of
// liability) for any loss or damage of any kind or nature
// related to, arising under or in connection with these
// materials, including for any direct, or any indirect,
// special, incidental, or consequential loss or damage
// (including loss of data, profits, goodwill, or any type of
// loss or damage suffered as a result of any action brought
// by a third party) even if such damage or loss was
// reasonably foreseeable or Xilinx had been advised of the
// possibility of the same.
// 
// CRITICAL APPLICATIONS
// Xilinx products are not designed or intended to be fail-
// safe, or for use in any application requiring fail-safe
// performance, such as life-support or safety devices or
// systems, Class III medical devices, nuclear facilities,
// applications related to the deployment of airbags, or any
// other applications that could lead to death, personal
// injury, or severe property or environmental damage
// (individually and collectively, "Critical
// Applications"). Customer assumes the sole risk and
// liability of any use of Xilinx products in Critical
// Applications, subject only to applicable laws and
// regulations governing limitations on product liability.
// 
// THIS COPYRIGHT NOTICE AND DISCLAIMER MUST BE RETAINED AS
// PART OF THIS FILE AT ALL TIMES. 


`default_nettype wire

`timescale 1ns / 1ps
`define DLY #1

//***************************** Entity Declaration ****************************

(* CORE_GENERATION_INFO = "system_displayport_0_0_gt_7_series_wrapper_4,gtwizard_v2_5,{protocol_file=display_port}" *) module system_displayport_0_0_gt_7_series_wrapper_4 #
(
    // Simulation attributes
    parameter   WRAPPER_SIM_GTRESET_SPEEDUP    =   "false",     // Set to "true" to speed up sim reset
    parameter   RX_DFE_KL_CFG2_IN              =   32'h3190D86C, //32'h3190180C,
    parameter   PMA_RSV_IN                     =   32'h00018480,
    parameter   SIM_VERSION                    =   "4.0"
)
(
    //_________________________________________________________________________
    //_________________________________________________________________________
    //GT0  (X0Y4)
    //____________________________CHANNEL PORTS________________________________
    //------------------------------- CPLL Ports -------------------------------
    output          GT0_CPLLFBCLKLOST_OUT,
    output          GT0_CPLLLOCK_OUT,
    input           GT0_CPLLLOCKDETCLK_IN,
    output          GT0_CPLLREFCLKLOST_OUT,
    input           GT0_CPLLRESET_IN,
    //------------------------ Channel - Clocking Ports ------------------------
    input           GT0_GTREFCLK0_IN,
    input           GT0_GTREFCLK1_IN,
    input   [2:0]   GT0_GTREFCLKSEL_IN,
    //-------------------------- Channel - DRP Ports  --------------------------
    input   [8:0]   GT0_DRPADDR_IN,
    input           GT0_DRPCLK_IN,
    input   [15:0]  GT0_DRPDI_IN,
    output  [15:0]  GT0_DRPDO_OUT,
    input           GT0_DRPEN_IN,
    output          GT0_DRPRDY_OUT,
    input           GT0_DRPWE_IN,
    //---------------------------- Power-Down Ports ----------------------------
    input   [1:0]   GT0_RXPD_IN,
    input   [1:0]   GT0_TXPD_IN,
    //------------------- RX Initialization and Reset Ports --------------------
    input           GT0_RXUSERRDY_IN,
    //------------------------ RX Margin Analysis Ports ------------------------
    output          GT0_EYESCANDATAERROR_OUT,
    //----------------------- Receive Ports - CDR Ports ------------------------
    output          GT0_RXCDRLOCK_OUT,
    //---------------- Receive Ports - FPGA RX Interface Ports -----------------
    input           GT0_RXUSRCLK_IN,
    input           GT0_RXUSRCLK2_IN,
    //---------------- Receive Ports - FPGA RX interface Ports -----------------
    output  [31:0]  GT0_RXDATA_OUT,
    //----------------- Receive Ports - Pattern Checker Ports ------------------
    output          GT0_RXPRBSERR_OUT,
    input   [2:0]   GT0_RXPRBSSEL_IN,
    //----------------- Receive Ports - Pattern Checker ports ------------------
    input           GT0_RXPRBSCNTRESET_IN,
    //---------------- Receive Ports - RX 8B/10B Decoder Ports -----------------
    output  [3:0]   GT0_RXDISPERR_OUT,
    output  [3:0]   GT0_RXNOTINTABLE_OUT,
    input           GT0_RX8B10BEN_IN,
    //------------------------- Receive Ports - RX AFE -------------------------
    input           GT0_GTXRXP_IN,
    //---------------------- Receive Ports - RX AFE Ports ----------------------
    input           GT0_GTXRXN_IN,
    //----------------- Receive Ports - RX Buffer Bypass Ports -----------------
    input           GT0_RXBUFRESET_IN,
    output  [2:0]   GT0_RXBUFSTATUS_OUT,
    //------------ Receive Ports - RX Byte and Word Alignment Ports ------------
    output          GT0_RXBYTEISALIGNED_OUT,
    input           GT0_RXMCOMMAALIGNEN_IN,
    input           GT0_RXPCOMMAALIGNEN_IN,
    output          GT0_RXCOMMADET_OUT,
    output          GT0_RXELECIDLE_OUT,
    //------------------- Receive Ports - RX Equalizer Ports -------------------
    input           GT0_RXDFELPMRESET_IN,
    //------------------- Receive Ports - RX Equilizer Ports -------------------
    input           GT0_RXLPMHFHOLD_IN,
    input           GT0_RXLPMLFHOLD_IN,
    //------------- Receive Ports - RX Fabric Output Control Ports -------------
    output          GT0_RXOUTCLK_OUT,
    //----------- Receive Ports - RX Initialization and Reset Ports ------------
    input           GT0_GTRXRESET_IN,
    input           GT0_RXPCSRESET_IN,
    input           GT0_RXPMARESET_IN,
    //---------------- Receive Ports - RX Margin Analysis ports ----------------
    input           GT0_RXLPMEN_IN,
    //----------------- Receive Ports - RX8B/10B Decoder Ports -----------------
    output  [3:0]   GT0_RXCHARISK_OUT,
    //------------ Receive Ports -RX Initialization and Reset Ports ------------
    output          GT0_RXRESETDONE_OUT,
    //---------------------- TX Configurable Driver Ports ----------------------
    input   [4:0]   GT0_TXPOSTCURSOR_IN,
    input   [4:0]   GT0_TXPRECURSOR_IN,
    //------------------- TX Initialization and Reset Ports --------------------
    input           GT0_GTTXRESET_IN,
    input           GT0_TXUSERRDY_IN,
    //-------------- Transmit Ports - 8b10b Encoder Control Ports --------------
    input   [3:0]   GT0_TXCHARDISPMODE_IN,
    input   [3:0]   GT0_TXCHARDISPVAL_IN,
    input           GT0_TX8B10BEN_IN,
    //---------------- Transmit Ports - FPGA TX Interface Ports ----------------
    input           GT0_TXUSRCLK_IN,
    input           GT0_TXUSRCLK2_IN,
    //---------------- Transmit Ports - Pattern Generator Ports ----------------
    input           GT0_TXPRBSFORCEERR_IN,
 
    //-------------------- Transmit Ports - TX Buffer Ports --------------------
    output  [1:0]   GT0_TXBUFSTATUS_OUT,
    //------------- Transmit Ports - TX Configurable Driver Ports --------------
    input   [3:0]   GT0_TXDIFFCTRL_IN,
    input           GT0_TXINHIBIT_IN,
    //---------------- Transmit Ports - TX Data Path interface -----------------
    input   [31:0]  GT0_TXDATA_IN,
    //-------------- Transmit Ports - TX Driver and OOB signaling --------------
    output          GT0_GTXTXN_OUT,
    output          GT0_GTXTXP_OUT,
    //--------- Transmit Ports - TX Fabric Clock Output Control Ports ----------
    output          GT0_TXOUTCLK_OUT,
    output          GT0_TXOUTCLKFABRIC_OUT,
    output          GT0_TXOUTCLKPCS_OUT,
    //------------------- Transmit Ports - TX Gearbox Ports --------------------
    input   [3:0]   GT0_TXCHARISK_IN,
    //----------- Transmit Ports - TX Initialization and Reset Ports -----------
    input           GT0_TXPCSRESET_IN,
    input           GT0_TXPMARESET_IN,
    output          GT0_TXRESETDONE_OUT,
    //---------------- Transmit Ports - pattern Generator Ports ----------------
    input   [2:0]   GT0_TXPRBSSEL_IN,

    //_________________________________________________________________________
    //_________________________________________________________________________
    //GT1  (X0Y5)
    //____________________________CHANNEL PORTS________________________________
    //------------------------------- CPLL Ports -------------------------------
    output          GT1_CPLLFBCLKLOST_OUT,
    output          GT1_CPLLLOCK_OUT,
    input           GT1_CPLLLOCKDETCLK_IN,
    output          GT1_CPLLREFCLKLOST_OUT,
    input           GT1_CPLLRESET_IN,
    //------------------------ Channel - Clocking Ports ------------------------
    input           GT1_GTREFCLK0_IN,
    input           GT1_GTREFCLK1_IN,
    input   [2:0]   GT1_GTREFCLKSEL_IN,
    //-------------------------- Channel - DRP Ports  --------------------------
    input   [8:0]   GT1_DRPADDR_IN,
    input           GT1_DRPCLK_IN,
    input   [15:0]  GT1_DRPDI_IN,
    output  [15:0]  GT1_DRPDO_OUT,
    input           GT1_DRPEN_IN,
    output          GT1_DRPRDY_OUT,
    input           GT1_DRPWE_IN,
    //---------------------------- Power-Down Ports ----------------------------
    input   [1:0]   GT1_RXPD_IN,
    input   [1:0]   GT1_TXPD_IN,
    //------------------- RX Initialization and Reset Ports --------------------
    input           GT1_RXUSERRDY_IN,
    //------------------------ RX Margin Analysis Ports ------------------------
    output          GT1_EYESCANDATAERROR_OUT,
    //----------------------- Receive Ports - CDR Ports ------------------------
    output          GT1_RXCDRLOCK_OUT,
    //---------------- Receive Ports - FPGA RX Interface Ports -----------------
    input           GT1_RXUSRCLK_IN,
    input           GT1_RXUSRCLK2_IN,
    //---------------- Receive Ports - FPGA RX interface Ports -----------------
    output  [31:0]  GT1_RXDATA_OUT,
    //----------------- Receive Ports - Pattern Checker Ports ------------------
    output          GT1_RXPRBSERR_OUT,
    input   [2:0]   GT1_RXPRBSSEL_IN,
    //----------------- Receive Ports - Pattern Checker ports ------------------
    input           GT1_RXPRBSCNTRESET_IN,
    //---------------- Receive Ports - RX 8B/10B Decoder Ports -----------------
    output  [3:0]   GT1_RXDISPERR_OUT,
    output  [3:0]   GT1_RXNOTINTABLE_OUT,
    input           GT1_RX8B10BEN_IN,
    //------------------------- Receive Ports - RX AFE -------------------------
    input           GT1_GTXRXP_IN,
    //---------------------- Receive Ports - RX AFE Ports ----------------------
    input           GT1_GTXRXN_IN,
    //----------------- Receive Ports - RX Buffer Bypass Ports -----------------
    input           GT1_RXBUFRESET_IN,
    output  [2:0]   GT1_RXBUFSTATUS_OUT,
    //------------ Receive Ports - RX Byte and Word Alignment Ports ------------
    output          GT1_RXBYTEISALIGNED_OUT,
    input           GT1_RXMCOMMAALIGNEN_IN,
    input           GT1_RXPCOMMAALIGNEN_IN,
    output          GT1_RXCOMMADET_OUT,
    output          GT1_RXELECIDLE_OUT,
    //------------------- Receive Ports - RX Equalizer Ports -------------------
    input           GT1_RXDFELPMRESET_IN,
    //------------------- Receive Ports - RX Equilizer Ports -------------------
    input           GT1_RXLPMHFHOLD_IN,
    input           GT1_RXLPMLFHOLD_IN,
    //------------- Receive Ports - RX Fabric Output Control Ports -------------
    output          GT1_RXOUTCLK_OUT,
    //----------- Receive Ports - RX Initialization and Reset Ports ------------
    input           GT1_GTRXRESET_IN,
    input           GT1_RXPCSRESET_IN,
    input           GT1_RXPMARESET_IN,
    //---------------- Receive Ports - RX Margin Analysis ports ----------------
    input           GT1_RXLPMEN_IN,
    //----------------- Receive Ports - RX8B/10B Decoder Ports -----------------
    output  [3:0]   GT1_RXCHARISK_OUT,
    //------------ Receive Ports -RX Initialization and Reset Ports ------------
    output          GT1_RXRESETDONE_OUT,
    //---------------------- TX Configurable Driver Ports ----------------------
    input   [4:0]   GT1_TXPOSTCURSOR_IN,
    input   [4:0]   GT1_TXPRECURSOR_IN,
    //------------------- TX Initialization and Reset Ports --------------------
    input           GT1_GTTXRESET_IN,
    input           GT1_TXUSERRDY_IN,
    //-------------- Transmit Ports - 8b10b Encoder Control Ports --------------
    input   [3:0]   GT1_TXCHARDISPMODE_IN,
    input   [3:0]   GT1_TXCHARDISPVAL_IN,
    input           GT1_TX8B10BEN_IN,
    //---------------- Transmit Ports - FPGA TX Interface Ports ----------------
    input           GT1_TXUSRCLK_IN,
    input           GT1_TXUSRCLK2_IN,
    //---------------- Transmit Ports - Pattern Generator Ports ----------------
    input           GT1_TXPRBSFORCEERR_IN,
 
    //-------------------- Transmit Ports - TX Buffer Ports --------------------
    output  [1:0]   GT1_TXBUFSTATUS_OUT,
    //------------- Transmit Ports - TX Configurable Driver Ports --------------
    input   [3:0]   GT1_TXDIFFCTRL_IN,
    input           GT1_TXINHIBIT_IN,
    //---------------- Transmit Ports - TX Data Path interface -----------------
    input   [31:0]  GT1_TXDATA_IN,
    //-------------- Transmit Ports - TX Driver and OOB signaling --------------
    output          GT1_GTXTXN_OUT,
    output          GT1_GTXTXP_OUT,
    //--------- Transmit Ports - TX Fabric Clock Output Control Ports ----------
    output          GT1_TXOUTCLK_OUT,
    output          GT1_TXOUTCLKFABRIC_OUT,
    output          GT1_TXOUTCLKPCS_OUT,
    //------------------- Transmit Ports - TX Gearbox Ports --------------------
    input   [3:0]   GT1_TXCHARISK_IN,
    //----------- Transmit Ports - TX Initialization and Reset Ports -----------
    input           GT1_TXPCSRESET_IN,
    input           GT1_TXPMARESET_IN,
    output          GT1_TXRESETDONE_OUT,
    //---------------- Transmit Ports - pattern Generator Ports ----------------
    input   [2:0]   GT1_TXPRBSSEL_IN,

    //_________________________________________________________________________
    //_________________________________________________________________________
    //GT2  (X0Y6)
    //____________________________CHANNEL PORTS________________________________
    //------------------------------- CPLL Ports -------------------------------
    output          GT2_CPLLFBCLKLOST_OUT,
    output          GT2_CPLLLOCK_OUT,
    input           GT2_CPLLLOCKDETCLK_IN,
    output          GT2_CPLLREFCLKLOST_OUT,
    input           GT2_CPLLRESET_IN,
    //------------------------ Channel - Clocking Ports ------------------------
    input           GT2_GTREFCLK0_IN,
    input           GT2_GTREFCLK1_IN,
    input   [2:0]   GT2_GTREFCLKSEL_IN,
    //-------------------------- Channel - DRP Ports  --------------------------
    input   [8:0]   GT2_DRPADDR_IN,
    input           GT2_DRPCLK_IN,
    input   [15:0]  GT2_DRPDI_IN,
    output  [15:0]  GT2_DRPDO_OUT,
    input           GT2_DRPEN_IN,
    output          GT2_DRPRDY_OUT,
    input           GT2_DRPWE_IN,
    //---------------------------- Power-Down Ports ----------------------------
    input   [1:0]   GT2_RXPD_IN,
    input   [1:0]   GT2_TXPD_IN,
    //------------------- RX Initialization and Reset Ports --------------------
    input           GT2_RXUSERRDY_IN,
    //------------------------ RX Margin Analysis Ports ------------------------
    output          GT2_EYESCANDATAERROR_OUT,
    //----------------------- Receive Ports - CDR Ports ------------------------
    output          GT2_RXCDRLOCK_OUT,
    //---------------- Receive Ports - FPGA RX Interface Ports -----------------
    input           GT2_RXUSRCLK_IN,
    input           GT2_RXUSRCLK2_IN,
    //---------------- Receive Ports - FPGA RX interface Ports -----------------
    output  [31:0]  GT2_RXDATA_OUT,
    //----------------- Receive Ports - Pattern Checker Ports ------------------
    output          GT2_RXPRBSERR_OUT,
    input   [2:0]   GT2_RXPRBSSEL_IN,
    //----------------- Receive Ports - Pattern Checker ports ------------------
    input           GT2_RXPRBSCNTRESET_IN,
    //---------------- Receive Ports - RX 8B/10B Decoder Ports -----------------
    output  [3:0]   GT2_RXDISPERR_OUT,
    output  [3:0]   GT2_RXNOTINTABLE_OUT,
    input           GT2_RX8B10BEN_IN,
    //------------------------- Receive Ports - RX AFE -------------------------
    input           GT2_GTXRXP_IN,
    //---------------------- Receive Ports - RX AFE Ports ----------------------
    input           GT2_GTXRXN_IN,
    //----------------- Receive Ports - RX Buffer Bypass Ports -----------------
    input           GT2_RXBUFRESET_IN,
    output  [2:0]   GT2_RXBUFSTATUS_OUT,
    //------------ Receive Ports - RX Byte and Word Alignment Ports ------------
    output          GT2_RXBYTEISALIGNED_OUT,
    input           GT2_RXMCOMMAALIGNEN_IN,
    input           GT2_RXPCOMMAALIGNEN_IN,
    output          GT2_RXCOMMADET_OUT,
    output          GT2_RXELECIDLE_OUT,
    //------------------- Receive Ports - RX Equalizer Ports -------------------
    input           GT2_RXDFELPMRESET_IN,
    //------------------- Receive Ports - RX Equilizer Ports -------------------
    input           GT2_RXLPMHFHOLD_IN,
    input           GT2_RXLPMLFHOLD_IN,
    //------------- Receive Ports - RX Fabric Output Control Ports -------------
    output          GT2_RXOUTCLK_OUT,
    //----------- Receive Ports - RX Initialization and Reset Ports ------------
    input           GT2_GTRXRESET_IN,
    input           GT2_RXPCSRESET_IN,
    input           GT2_RXPMARESET_IN,
    //---------------- Receive Ports - RX Margin Analysis ports ----------------
    input           GT2_RXLPMEN_IN,
    //----------------- Receive Ports - RX8B/10B Decoder Ports -----------------
    output  [3:0]   GT2_RXCHARISK_OUT,
    //------------ Receive Ports -RX Initialization and Reset Ports ------------
    output          GT2_RXRESETDONE_OUT,
    //---------------------- TX Configurable Driver Ports ----------------------
    input   [4:0]   GT2_TXPOSTCURSOR_IN,
    input   [4:0]   GT2_TXPRECURSOR_IN,
    //------------------- TX Initialization and Reset Ports --------------------
    input           GT2_GTTXRESET_IN,
    input           GT2_TXUSERRDY_IN,
    //-------------- Transmit Ports - 8b10b Encoder Control Ports --------------
    input   [3:0]   GT2_TXCHARDISPMODE_IN,
    input   [3:0]   GT2_TXCHARDISPVAL_IN,
    input           GT2_TX8B10BEN_IN,
    //---------------- Transmit Ports - FPGA TX Interface Ports ----------------
    input           GT2_TXUSRCLK_IN,
    input           GT2_TXUSRCLK2_IN,
    //---------------- Transmit Ports - Pattern Generator Ports ----------------
    input           GT2_TXPRBSFORCEERR_IN,
 
    //-------------------- Transmit Ports - TX Buffer Ports --------------------
    output  [1:0]   GT2_TXBUFSTATUS_OUT,
    //------------- Transmit Ports - TX Configurable Driver Ports --------------
    input   [3:0]   GT2_TXDIFFCTRL_IN,
    input           GT2_TXINHIBIT_IN,
    //---------------- Transmit Ports - TX Data Path interface -----------------
    input   [31:0]  GT2_TXDATA_IN,
    //-------------- Transmit Ports - TX Driver and OOB signaling --------------
    output          GT2_GTXTXN_OUT,
    output          GT2_GTXTXP_OUT,
    //--------- Transmit Ports - TX Fabric Clock Output Control Ports ----------
    output          GT2_TXOUTCLK_OUT,
    output          GT2_TXOUTCLKFABRIC_OUT,
    output          GT2_TXOUTCLKPCS_OUT,
    //------------------- Transmit Ports - TX Gearbox Ports --------------------
    input   [3:0]   GT2_TXCHARISK_IN,
    //----------- Transmit Ports - TX Initialization and Reset Ports -----------
    input           GT2_TXPCSRESET_IN,
    input           GT2_TXPMARESET_IN,
    output          GT2_TXRESETDONE_OUT,
    //---------------- Transmit Ports - pattern Generator Ports ----------------
    input   [2:0]   GT2_TXPRBSSEL_IN,

    //_________________________________________________________________________
    //_________________________________________________________________________
    //GT3  (X0Y7)
    //____________________________CHANNEL PORTS________________________________
    //------------------------------- CPLL Ports -------------------------------
    output          GT3_CPLLFBCLKLOST_OUT,
    output          GT3_CPLLLOCK_OUT,
    input           GT3_CPLLLOCKDETCLK_IN,
    output          GT3_CPLLREFCLKLOST_OUT,
    input           GT3_CPLLRESET_IN,
    //------------------------ Channel - Clocking Ports ------------------------
    input           GT3_GTREFCLK0_IN,
    input           GT3_GTREFCLK1_IN,
    input   [2:0]   GT3_GTREFCLKSEL_IN,
    //-------------------------- Channel - DRP Ports  --------------------------
    input   [8:0]   GT3_DRPADDR_IN,
    input           GT3_DRPCLK_IN,
    input   [15:0]  GT3_DRPDI_IN,
    output  [15:0]  GT3_DRPDO_OUT,
    input           GT3_DRPEN_IN,
    output          GT3_DRPRDY_OUT,
    input           GT3_DRPWE_IN,
    //---------------------------- Power-Down Ports ----------------------------
    input   [1:0]   GT3_RXPD_IN,
    input   [1:0]   GT3_TXPD_IN,
    //------------------- RX Initialization and Reset Ports --------------------
    input           GT3_RXUSERRDY_IN,
    //------------------------ RX Margin Analysis Ports ------------------------
    output          GT3_EYESCANDATAERROR_OUT,
    //----------------------- Receive Ports - CDR Ports ------------------------
    output          GT3_RXCDRLOCK_OUT,
    //---------------- Receive Ports - FPGA RX Interface Ports -----------------
    input           GT3_RXUSRCLK_IN,
    input           GT3_RXUSRCLK2_IN,
    //---------------- Receive Ports - FPGA RX interface Ports -----------------
    output  [31:0]  GT3_RXDATA_OUT,
    //----------------- Receive Ports - Pattern Checker Ports ------------------
    output          GT3_RXPRBSERR_OUT,
    input   [2:0]   GT3_RXPRBSSEL_IN,
    //----------------- Receive Ports - Pattern Checker ports ------------------
    input           GT3_RXPRBSCNTRESET_IN,
    //---------------- Receive Ports - RX 8B/10B Decoder Ports -----------------
    output  [3:0]   GT3_RXDISPERR_OUT,
    output  [3:0]   GT3_RXNOTINTABLE_OUT,
    input           GT3_RX8B10BEN_IN,
    //------------------------- Receive Ports - RX AFE -------------------------
    input           GT3_GTXRXP_IN,
    //---------------------- Receive Ports - RX AFE Ports ----------------------
    input           GT3_GTXRXN_IN,
    //----------------- Receive Ports - RX Buffer Bypass Ports -----------------
    input           GT3_RXBUFRESET_IN,
    output  [2:0]   GT3_RXBUFSTATUS_OUT,
    //------------ Receive Ports - RX Byte and Word Alignment Ports ------------
    output          GT3_RXBYTEISALIGNED_OUT,
    input           GT3_RXMCOMMAALIGNEN_IN,
    input           GT3_RXPCOMMAALIGNEN_IN,
    output          GT3_RXCOMMADET_OUT,
    output          GT3_RXELECIDLE_OUT,
    //------------------- Receive Ports - RX Equalizer Ports -------------------
    input           GT3_RXDFELPMRESET_IN,
    //------------------- Receive Ports - RX Equilizer Ports -------------------
    input           GT3_RXLPMHFHOLD_IN,
    input           GT3_RXLPMLFHOLD_IN,
    //------------- Receive Ports - RX Fabric Output Control Ports -------------
    output          GT3_RXOUTCLK_OUT,
    //----------- Receive Ports - RX Initialization and Reset Ports ------------
    input           GT3_GTRXRESET_IN,
    input           GT3_RXPCSRESET_IN,
    input           GT3_RXPMARESET_IN,
    //---------------- Receive Ports - RX Margin Analysis ports ----------------
    input           GT3_RXLPMEN_IN,
    //----------------- Receive Ports - RX8B/10B Decoder Ports -----------------
    output  [3:0]   GT3_RXCHARISK_OUT,
    //------------ Receive Ports -RX Initialization and Reset Ports ------------
    output          GT3_RXRESETDONE_OUT,
    //---------------------- TX Configurable Driver Ports ----------------------
    input   [4:0]   GT3_TXPOSTCURSOR_IN,
    input   [4:0]   GT3_TXPRECURSOR_IN,
    //------------------- TX Initialization and Reset Ports --------------------
    input           GT3_GTTXRESET_IN,
    input           GT3_TXUSERRDY_IN,
    //-------------- Transmit Ports - 8b10b Encoder Control Ports --------------
    input   [3:0]   GT3_TXCHARDISPMODE_IN,
    input   [3:0]   GT3_TXCHARDISPVAL_IN,
    input           GT3_TX8B10BEN_IN,
    //---------------- Transmit Ports - FPGA TX Interface Ports ----------------
    input           GT3_TXUSRCLK_IN,
    input           GT3_TXUSRCLK2_IN,
    //---------------- Transmit Ports - Pattern Generator Ports ----------------
    input           GT3_TXPRBSFORCEERR_IN,
 
    //-------------------- Transmit Ports - TX Buffer Ports --------------------
    output  [1:0]   GT3_TXBUFSTATUS_OUT,
    //------------- Transmit Ports - TX Configurable Driver Ports --------------
    input   [3:0]   GT3_TXDIFFCTRL_IN,
    input           GT3_TXINHIBIT_IN,
    //---------------- Transmit Ports - TX Data Path interface -----------------
    input   [31:0]  GT3_TXDATA_IN,
    //-------------- Transmit Ports - TX Driver and OOB signaling --------------
    output          GT3_GTXTXN_OUT,
    output          GT3_GTXTXP_OUT,
    //--------- Transmit Ports - TX Fabric Clock Output Control Ports ----------
    output          GT3_TXOUTCLK_OUT,
    output          GT3_TXOUTCLKFABRIC_OUT,
    output          GT3_TXOUTCLKPCS_OUT,
    //------------------- Transmit Ports - TX Gearbox Ports --------------------
    input   [3:0]   GT3_TXCHARISK_IN,
    //----------- Transmit Ports - TX Initialization and Reset Ports -----------
    input           GT3_TXPCSRESET_IN,
    input           GT3_TXPMARESET_IN,
    output          GT3_TXRESETDONE_OUT,
    //---------------- Transmit Ports - pattern Generator Ports ----------------
    input   [2:0]   GT3_TXPRBSSEL_IN,

    //DFE HOLD PORTS
    input           GT0_RXDFEAGCHOLD_IN,
    input           GT0_RXDFELFHOLD_IN,
    input           GT1_RXDFEAGCHOLD_IN,
    input           GT1_RXDFELFHOLD_IN,
    input           GT2_RXDFEAGCHOLD_IN,
    input           GT2_RXDFELFHOLD_IN,
    input           GT3_RXDFEAGCHOLD_IN,
    input           GT3_RXDFELFHOLD_IN,

    //COMMON PORTS
    input           GT0_QPLLCLK_IN,
    input           GT0_QPLLREFCLK_IN,

    // Debug ports
    input           GT0_EYESCANRESET_IN,     
    input           GT0_EYESCANTRIGGER_IN,   
    input           GT0_RXPOLARITY_IN,   
    input           GT0_TXPOLARITY_IN,   
    input   [2:0]   GT0_LOOPBACK_IN,
    output  [7:0]   GT0_DMONITOROUT_OUT,
    input           GT0_RXCDRHOLD_IN,
    input           GT0_RXLPMHFOVRDEN_IN,

    input           GT1_EYESCANRESET_IN,     
    input           GT1_EYESCANTRIGGER_IN,   
    input           GT1_RXPOLARITY_IN,   
    input           GT1_TXPOLARITY_IN,   
    input   [2:0]   GT1_LOOPBACK_IN,
    output  [7:0]   GT1_DMONITOROUT_OUT,
    input           GT1_RXCDRHOLD_IN,
    input           GT1_RXLPMHFOVRDEN_IN,

    input           GT2_EYESCANRESET_IN,     
    input           GT2_EYESCANTRIGGER_IN,   
    input           GT2_RXPOLARITY_IN,   
    input           GT2_TXPOLARITY_IN,   
    input   [2:0]   GT2_LOOPBACK_IN,
    output  [7:0]   GT2_DMONITOROUT_OUT,
    input           GT2_RXCDRHOLD_IN,
    input           GT2_RXLPMHFOVRDEN_IN,

    input           GT3_EYESCANRESET_IN,     
    input           GT3_EYESCANTRIGGER_IN,   
    input           GT3_RXPOLARITY_IN,   
    input           GT3_TXPOLARITY_IN,   
    input   [2:0]   GT3_LOOPBACK_IN,
    output  [7:0]   GT3_DMONITOROUT_OUT,
    input           GT3_RXCDRHOLD_IN,
    input           GT3_RXLPMHFOVRDEN_IN 

);
 
//------------------------- GT Instances  -------------------------------
    //_________________________________________________________________________
    //_________________________________________________________________________
    //GT0  (X0Y4)

    system_displayport_0_0_gt_7_series_wrapper_4_GT #
    (
        // Simulation attributes
        .GT_SIM_GTRESET_SPEEDUP   (WRAPPER_SIM_GTRESET_SPEEDUP),
        .SIM_VERSION              (SIM_VERSION),
        .RX_DFE_KL_CFG2_IN        (RX_DFE_KL_CFG2_IN),
        .PCS_RSVD_ATTR_IN         (48'h000000000000),
        .PMA_RSV_IN               (PMA_RSV_IN)
    )
    gt0_gt_7_series_wrapper_4_i
    (
        //------------------------------- CPLL Ports -------------------------------
        .CPLLFBCLKLOST_OUT              (GT0_CPLLFBCLKLOST_OUT),
        .CPLLLOCK_OUT                   (GT0_CPLLLOCK_OUT),
        .CPLLLOCKDETCLK_IN              (GT0_CPLLLOCKDETCLK_IN),
        .CPLLREFCLKLOST_OUT             (GT0_CPLLREFCLKLOST_OUT),
        .CPLLRESET_IN                   (GT0_CPLLRESET_IN),
        //------------------------ Channel - Clocking Ports ------------------------
        .GTREFCLK0_IN                   (GT0_GTREFCLK0_IN),
        .GTREFCLK1_IN                   (GT0_GTREFCLK1_IN),
        .GTREFCLKSEL_IN                 (GT0_GTREFCLKSEL_IN),
        //-------------------------- Channel - DRP Ports  --------------------------
        .DRPADDR_IN                     (GT0_DRPADDR_IN),
        .DRPCLK_IN                      (GT0_DRPCLK_IN),
        .DRPDI_IN                       (GT0_DRPDI_IN),
        .DRPDO_OUT                      (GT0_DRPDO_OUT),
        .DRPEN_IN                       (GT0_DRPEN_IN),
        .DRPRDY_OUT                     (GT0_DRPRDY_OUT),
        .DRPWE_IN                       (GT0_DRPWE_IN),
        .TXPOLARITY_IN                  (GT0_TXPOLARITY_IN),
        .RXPOLARITY_IN                  (GT0_RXPOLARITY_IN),
        .LOOPBACK_IN                    (GT0_LOOPBACK_IN),
        .DMONITOROUT_OUT                (GT0_DMONITOROUT_OUT),
        .RXLPMHFOVRDEN_IN               (GT0_RXLPMHFOVRDEN_IN),
        .RXCDRHOLD_IN                   (GT0_RXCDRHOLD_IN),
        //----------------------------- Clocking Ports -----------------------------
        .QPLLCLK_IN                     (GT0_QPLLCLK_IN),
        .QPLLREFCLK_IN                  (GT0_QPLLREFCLK_IN),
        //---------------------------- Power-Down Ports ----------------------------
        .RXPD_IN                        (GT0_RXPD_IN),
        .TXPD_IN                        (GT0_TXPD_IN),
        //------------------- RX Initialization and Reset Ports --------------------
        .RXUSERRDY_IN                   (GT0_RXUSERRDY_IN),
        //------------------------ RX Margin Analysis Ports ------------------------
        .EYESCANRESET_IN                (GT0_EYESCANRESET_IN),
        .EYESCANTRIGGER_IN              (GT0_EYESCANTRIGGER_IN),
        .EYESCANDATAERROR_OUT           (GT0_EYESCANDATAERROR_OUT),
        //----------------------- Receive Ports - CDR Ports ------------------------
        .RXCDRLOCK_OUT                  (GT0_RXCDRLOCK_OUT),
        //---------------- Receive Ports - FPGA RX Interface Ports -----------------
        .RXUSRCLK_IN                    (GT0_RXUSRCLK_IN),
        .RXUSRCLK2_IN                   (GT0_RXUSRCLK2_IN),
        //---------------- Receive Ports - FPGA RX interface Ports -----------------
        .RXDATA_OUT                     (GT0_RXDATA_OUT),
        //----------------- Receive Ports - Pattern Checker Ports ------------------
        .RXPRBSERR_OUT                  (GT0_RXPRBSERR_OUT),
        .RXPRBSSEL_IN                   (GT0_RXPRBSSEL_IN),
        //----------------- Receive Ports - Pattern Checker ports ------------------
        .RXPRBSCNTRESET_IN              (GT0_RXPRBSCNTRESET_IN),
        //---------------- Receive Ports - RX 8B/10B Decoder Ports -----------------
        .RXDISPERR_OUT                  (GT0_RXDISPERR_OUT),
        .RXNOTINTABLE_OUT               (GT0_RXNOTINTABLE_OUT),
        .RX8B10BEN_IN                   (GT0_RX8B10BEN_IN),
        //------------------------- Receive Ports - RX AFE -------------------------
        .GTXRXP_IN                      (GT0_GTXRXP_IN),
        //---------------------- Receive Ports - RX AFE Ports ----------------------
        .GTXRXN_IN                      (GT0_GTXRXN_IN),
        //----------------- Receive Ports - RX Buffer Bypass Ports -----------------
        .RXBUFRESET_IN                  (GT0_RXBUFRESET_IN),
        .RXBUFSTATUS_OUT                (GT0_RXBUFSTATUS_OUT),
        //------------ Receive Ports - RX Byte and Word Alignment Ports ------------
        .RXBYTEISALIGNED_OUT            (GT0_RXBYTEISALIGNED_OUT),
        .RXMCOMMAALIGNEN_IN             (GT0_RXMCOMMAALIGNEN_IN),
        .RXPCOMMAALIGNEN_IN             (GT0_RXPCOMMAALIGNEN_IN),
        .RXCOMMADET_OUT                 (GT0_RXCOMMADET_OUT),
        .RXELECIDLE_OUT                 (GT0_RXELECIDLE_OUT),
        //------------------- Receive Ports - RX Equalizer Ports -------------------
        .RXDFELPMRESET_IN               (GT0_RXDFELPMRESET_IN),
        //------------------- Receive Ports - RX Equilizer Ports -------------------
        .RXLPMHFHOLD_IN                 (GT0_RXLPMHFHOLD_IN),
        .RXLPMLFHOLD_IN                 (GT0_RXLPMLFHOLD_IN),
        .RXDFEAGCHOLD_IN                (GT0_RXDFEAGCHOLD_IN),
        .RXDFELFHOLD_IN                 (GT0_RXDFELFHOLD_IN),
        //------------- Receive Ports - RX Fabric Output Control Ports -------------
        .RXOUTCLK_OUT                   (GT0_RXOUTCLK_OUT),
        //----------- Receive Ports - RX Initialization and Reset Ports ------------
        .GTRXRESET_IN                   (GT0_GTRXRESET_IN),
        .RXPCSRESET_IN                  (GT0_RXPCSRESET_IN),
        .RXPMARESET_IN                  (GT0_RXPMARESET_IN),
        //---------------- Receive Ports - RX Margin Analysis ports ----------------
        .RXLPMEN_IN                     (GT0_RXLPMEN_IN),
        //----------------- Receive Ports - RX8B/10B Decoder Ports -----------------
        .RXCHARISK_OUT                  (GT0_RXCHARISK_OUT),
        //------------ Receive Ports -RX Initialization and Reset Ports ------------
        .RXRESETDONE_OUT                (GT0_RXRESETDONE_OUT),
        //---------------------- TX Configurable Driver Ports ----------------------
        .TXPOSTCURSOR_IN                (GT0_TXPOSTCURSOR_IN),
        .TXPRECURSOR_IN                 (GT0_TXPRECURSOR_IN),
        //------------------- TX Initialization and Reset Ports --------------------
        .GTTXRESET_IN                   (GT0_GTTXRESET_IN),
        .TXUSERRDY_IN                   (GT0_TXUSERRDY_IN),
        //-------------- Transmit Ports - 8b10b Encoder Control Ports --------------
        .TXCHARDISPMODE_IN              (GT0_TXCHARDISPMODE_IN),
        .TXCHARDISPVAL_IN               (GT0_TXCHARDISPVAL_IN),
        .TX8B10BEN_IN                   (GT0_TX8B10BEN_IN),
        //---------------- Transmit Ports - FPGA TX Interface Ports ----------------
        .TXUSRCLK_IN                    (GT0_TXUSRCLK_IN),
        .TXUSRCLK2_IN                   (GT0_TXUSRCLK2_IN),
        //------------------- Transmit Ports - PCI Express Ports -------------------
        .TXELECIDLE_IN                  (1'b0),
        //---------------- Transmit Ports - Pattern Generator Ports ----------------
        .TXPRBSFORCEERR_IN              (GT0_TXPRBSFORCEERR_IN),
 
        //-------------------- Transmit Ports - TX Buffer Ports --------------------
        .TXBUFSTATUS_OUT                (GT0_TXBUFSTATUS_OUT),
        //------------- Transmit Ports - TX Configurable Driver Ports --------------
        .TXDIFFCTRL_IN                  (GT0_TXDIFFCTRL_IN),
        .TXINHIBIT_IN                   (GT0_TXINHIBIT_IN),
        //---------------- Transmit Ports - TX Data Path interface -----------------
        .TXDATA_IN                      (GT0_TXDATA_IN),
        //-------------- Transmit Ports - TX Driver and OOB signaling --------------
        .GTXTXN_OUT                     (GT0_GTXTXN_OUT),
        .GTXTXP_OUT                     (GT0_GTXTXP_OUT),
        //--------- Transmit Ports - TX Fabric Clock Output Control Ports ----------
        .TXOUTCLK_OUT                   (GT0_TXOUTCLK_OUT),
        .TXOUTCLKFABRIC_OUT             (GT0_TXOUTCLKFABRIC_OUT),
        .TXOUTCLKPCS_OUT                (GT0_TXOUTCLKPCS_OUT),
        //------------------- Transmit Ports - TX Gearbox Ports --------------------
        .TXCHARISK_IN                   (GT0_TXCHARISK_IN),
        //----------- Transmit Ports - TX Initialization and Reset Ports -----------
        .TXPCSRESET_IN                  (GT0_TXPCSRESET_IN),
        .TXPMARESET_IN                  (GT0_TXPMARESET_IN),
        .TXRESETDONE_OUT                (GT0_TXRESETDONE_OUT),
        //---------------- Transmit Ports - pattern Generator Ports ----------------
        .TXPRBSSEL_IN                   (GT0_TXPRBSSEL_IN)

    );

    //_________________________________________________________________________
    //_________________________________________________________________________
    //GT1  (X0Y5)

    system_displayport_0_0_gt_7_series_wrapper_4_GT #
    (
        // Simulation attributes
        .GT_SIM_GTRESET_SPEEDUP   (WRAPPER_SIM_GTRESET_SPEEDUP),
        .SIM_VERSION              (SIM_VERSION),
        .RX_DFE_KL_CFG2_IN        (RX_DFE_KL_CFG2_IN),
        .PCS_RSVD_ATTR_IN         (48'h000000000000),
        .PMA_RSV_IN               (PMA_RSV_IN)
    )
    gt1_gt_7_series_wrapper_4_i
    (
        //------------------------------- CPLL Ports -------------------------------
        .CPLLFBCLKLOST_OUT              (GT1_CPLLFBCLKLOST_OUT),
        .CPLLLOCK_OUT                   (GT1_CPLLLOCK_OUT),
        .CPLLLOCKDETCLK_IN              (GT1_CPLLLOCKDETCLK_IN),
        .CPLLREFCLKLOST_OUT             (GT1_CPLLREFCLKLOST_OUT),
        .CPLLRESET_IN                   (GT1_CPLLRESET_IN),
        //------------------------ Channel - Clocking Ports ------------------------
        .GTREFCLK0_IN                   (GT1_GTREFCLK0_IN),
        .GTREFCLK1_IN                   (GT1_GTREFCLK1_IN),
        .GTREFCLKSEL_IN                 (GT1_GTREFCLKSEL_IN),
        //-------------------------- Channel - DRP Ports  --------------------------
        .DRPADDR_IN                     (GT1_DRPADDR_IN),
        .DRPCLK_IN                      (GT1_DRPCLK_IN),
        .DRPDI_IN                       (GT1_DRPDI_IN),
        .DRPDO_OUT                      (GT1_DRPDO_OUT),
        .DRPEN_IN                       (GT1_DRPEN_IN),
        .DRPRDY_OUT                     (GT1_DRPRDY_OUT),
        .DRPWE_IN                       (GT1_DRPWE_IN),
        .TXPOLARITY_IN                  (GT1_TXPOLARITY_IN),
        .RXPOLARITY_IN                  (GT1_RXPOLARITY_IN),
        .LOOPBACK_IN                    (GT1_LOOPBACK_IN),
        .DMONITOROUT_OUT                (GT1_DMONITOROUT_OUT),
        .RXLPMHFOVRDEN_IN               (GT1_RXLPMHFOVRDEN_IN),
        .RXCDRHOLD_IN                   (GT1_RXCDRHOLD_IN),
        //----------------------------- Clocking Ports -----------------------------
        .QPLLCLK_IN                     (GT0_QPLLCLK_IN),
        .QPLLREFCLK_IN                  (GT0_QPLLREFCLK_IN),
        //---------------------------- Power-Down Ports ----------------------------
        .RXPD_IN                        (GT1_RXPD_IN),
        .TXPD_IN                        (GT1_TXPD_IN),
        //------------------- RX Initialization and Reset Ports --------------------
        .RXUSERRDY_IN                   (GT1_RXUSERRDY_IN),
        //------------------------ RX Margin Analysis Ports ------------------------
        .EYESCANRESET_IN                (GT1_EYESCANRESET_IN),
        .EYESCANTRIGGER_IN              (GT1_EYESCANTRIGGER_IN),
        .EYESCANDATAERROR_OUT           (GT1_EYESCANDATAERROR_OUT),
        //----------------------- Receive Ports - CDR Ports ------------------------
        .RXCDRLOCK_OUT                  (GT1_RXCDRLOCK_OUT),
        //---------------- Receive Ports - FPGA RX Interface Ports -----------------
        .RXUSRCLK_IN                    (GT1_RXUSRCLK_IN),
        .RXUSRCLK2_IN                   (GT1_RXUSRCLK2_IN),
        //---------------- Receive Ports - FPGA RX interface Ports -----------------
        .RXDATA_OUT                     (GT1_RXDATA_OUT),
        //----------------- Receive Ports - Pattern Checker Ports ------------------
        .RXPRBSERR_OUT                  (GT1_RXPRBSERR_OUT),
        .RXPRBSSEL_IN                   (GT1_RXPRBSSEL_IN),
        //----------------- Receive Ports - Pattern Checker ports ------------------
        .RXPRBSCNTRESET_IN              (GT1_RXPRBSCNTRESET_IN),
        //---------------- Receive Ports - RX 8B/10B Decoder Ports -----------------
        .RXDISPERR_OUT                  (GT1_RXDISPERR_OUT),
        .RXNOTINTABLE_OUT               (GT1_RXNOTINTABLE_OUT),
        .RX8B10BEN_IN                   (GT1_RX8B10BEN_IN),
        //------------------------- Receive Ports - RX AFE -------------------------
        .GTXRXP_IN                      (GT1_GTXRXP_IN),
        //---------------------- Receive Ports - RX AFE Ports ----------------------
        .GTXRXN_IN                      (GT1_GTXRXN_IN),
        //----------------- Receive Ports - RX Buffer Bypass Ports -----------------
        .RXBUFRESET_IN                  (GT1_RXBUFRESET_IN),
        .RXBUFSTATUS_OUT                (GT1_RXBUFSTATUS_OUT),
        //------------ Receive Ports - RX Byte and Word Alignment Ports ------------
        .RXBYTEISALIGNED_OUT            (GT1_RXBYTEISALIGNED_OUT),
        .RXMCOMMAALIGNEN_IN             (GT1_RXMCOMMAALIGNEN_IN),
        .RXPCOMMAALIGNEN_IN             (GT1_RXPCOMMAALIGNEN_IN),
        .RXCOMMADET_OUT                 (GT1_RXCOMMADET_OUT),
        .RXELECIDLE_OUT                 (GT1_RXELECIDLE_OUT),
        //------------------- Receive Ports - RX Equalizer Ports -------------------
        .RXDFELPMRESET_IN               (GT1_RXDFELPMRESET_IN),
        //------------------- Receive Ports - RX Equilizer Ports -------------------
        .RXLPMHFHOLD_IN                 (GT1_RXLPMHFHOLD_IN),
        .RXLPMLFHOLD_IN                 (GT1_RXLPMLFHOLD_IN),
        .RXDFEAGCHOLD_IN                (GT1_RXDFEAGCHOLD_IN),
        .RXDFELFHOLD_IN                 (GT1_RXDFELFHOLD_IN),
        //------------- Receive Ports - RX Fabric Output Control Ports -------------
        .RXOUTCLK_OUT                   (GT1_RXOUTCLK_OUT),
        //----------- Receive Ports - RX Initialization and Reset Ports ------------
        .GTRXRESET_IN                   (GT1_GTRXRESET_IN),
        .RXPCSRESET_IN                  (GT1_RXPCSRESET_IN),
        .RXPMARESET_IN                  (GT1_RXPMARESET_IN),
        //---------------- Receive Ports - RX Margin Analysis ports ----------------
        .RXLPMEN_IN                     (GT1_RXLPMEN_IN),
        //----------------- Receive Ports - RX8B/10B Decoder Ports -----------------
        .RXCHARISK_OUT                  (GT1_RXCHARISK_OUT),
        //------------ Receive Ports -RX Initialization and Reset Ports ------------
        .RXRESETDONE_OUT                (GT1_RXRESETDONE_OUT),
        //---------------------- TX Configurable Driver Ports ----------------------
        .TXPOSTCURSOR_IN                (GT1_TXPOSTCURSOR_IN),
        .TXPRECURSOR_IN                 (GT1_TXPRECURSOR_IN),
        //------------------- TX Initialization and Reset Ports --------------------
        .GTTXRESET_IN                   (GT1_GTTXRESET_IN),
        .TXUSERRDY_IN                   (GT1_TXUSERRDY_IN),
        //-------------- Transmit Ports - 8b10b Encoder Control Ports --------------
        .TXCHARDISPMODE_IN              (GT1_TXCHARDISPMODE_IN),
        .TXCHARDISPVAL_IN               (GT1_TXCHARDISPVAL_IN),
        .TX8B10BEN_IN                   (GT1_TX8B10BEN_IN),
        //---------------- Transmit Ports - FPGA TX Interface Ports ----------------
        .TXUSRCLK_IN                    (GT1_TXUSRCLK_IN),
        .TXUSRCLK2_IN                   (GT1_TXUSRCLK2_IN),
        //------------------- Transmit Ports - PCI Express Ports -------------------
        .TXELECIDLE_IN                  (1'b0),
        //---------------- Transmit Ports - Pattern Generator Ports ----------------
        .TXPRBSFORCEERR_IN              (GT1_TXPRBSFORCEERR_IN),
 
        //-------------------- Transmit Ports - TX Buffer Ports --------------------
        .TXBUFSTATUS_OUT                (GT1_TXBUFSTATUS_OUT),
        //------------- Transmit Ports - TX Configurable Driver Ports --------------
        .TXDIFFCTRL_IN                  (GT1_TXDIFFCTRL_IN),
        .TXINHIBIT_IN                   (GT1_TXINHIBIT_IN),
        //---------------- Transmit Ports - TX Data Path interface -----------------
        .TXDATA_IN                      (GT1_TXDATA_IN),
        //-------------- Transmit Ports - TX Driver and OOB signaling --------------
        .GTXTXN_OUT                     (GT1_GTXTXN_OUT),
        .GTXTXP_OUT                     (GT1_GTXTXP_OUT),
        //--------- Transmit Ports - TX Fabric Clock Output Control Ports ----------
        .TXOUTCLK_OUT                   (GT1_TXOUTCLK_OUT),
        .TXOUTCLKFABRIC_OUT             (GT1_TXOUTCLKFABRIC_OUT),
        .TXOUTCLKPCS_OUT                (GT1_TXOUTCLKPCS_OUT),
        //------------------- Transmit Ports - TX Gearbox Ports --------------------
        .TXCHARISK_IN                   (GT1_TXCHARISK_IN),
        //----------- Transmit Ports - TX Initialization and Reset Ports -----------
        .TXPCSRESET_IN                  (GT1_TXPCSRESET_IN),
        .TXPMARESET_IN                  (GT1_TXPMARESET_IN),
        .TXRESETDONE_OUT                (GT1_TXRESETDONE_OUT),
        //---------------- Transmit Ports - pattern Generator Ports ----------------
        .TXPRBSSEL_IN                   (GT1_TXPRBSSEL_IN)

    );

    //_________________________________________________________________________
    //_________________________________________________________________________
    //GT2  (X0Y6)

    system_displayport_0_0_gt_7_series_wrapper_4_GT #
    (
        // Simulation attributes
        .GT_SIM_GTRESET_SPEEDUP   (WRAPPER_SIM_GTRESET_SPEEDUP),
        .SIM_VERSION              (SIM_VERSION),
        .RX_DFE_KL_CFG2_IN        (RX_DFE_KL_CFG2_IN),
        .PCS_RSVD_ATTR_IN         (48'h000000000000),
        .PMA_RSV_IN               (PMA_RSV_IN)
    )
    gt2_gt_7_series_wrapper_4_i
    (
        //------------------------------- CPLL Ports -------------------------------
        .CPLLFBCLKLOST_OUT              (GT2_CPLLFBCLKLOST_OUT),
        .CPLLLOCK_OUT                   (GT2_CPLLLOCK_OUT),
        .CPLLLOCKDETCLK_IN              (GT2_CPLLLOCKDETCLK_IN),
        .CPLLREFCLKLOST_OUT             (GT2_CPLLREFCLKLOST_OUT),
        .CPLLRESET_IN                   (GT2_CPLLRESET_IN),
        //------------------------ Channel - Clocking Ports ------------------------
        .GTREFCLK0_IN                   (GT2_GTREFCLK0_IN),
        .GTREFCLK1_IN                   (GT2_GTREFCLK1_IN),
        .GTREFCLKSEL_IN                 (GT2_GTREFCLKSEL_IN),
        //-------------------------- Channel - DRP Ports  --------------------------
        .DRPADDR_IN                     (GT2_DRPADDR_IN),
        .DRPCLK_IN                      (GT2_DRPCLK_IN),
        .DRPDI_IN                       (GT2_DRPDI_IN),
        .DRPDO_OUT                      (GT2_DRPDO_OUT),
        .DRPEN_IN                       (GT2_DRPEN_IN),
        .DRPRDY_OUT                     (GT2_DRPRDY_OUT),
        .DRPWE_IN                       (GT2_DRPWE_IN),
        .TXPOLARITY_IN                  (GT2_TXPOLARITY_IN),
        .RXPOLARITY_IN                  (GT2_RXPOLARITY_IN),
        .LOOPBACK_IN                    (GT2_LOOPBACK_IN),
        .DMONITOROUT_OUT                (GT2_DMONITOROUT_OUT),
        .RXLPMHFOVRDEN_IN               (GT2_RXLPMHFOVRDEN_IN),
        .RXCDRHOLD_IN                   (GT2_RXCDRHOLD_IN),
        //----------------------------- Clocking Ports -----------------------------
        .QPLLCLK_IN                     (GT0_QPLLCLK_IN),
        .QPLLREFCLK_IN                  (GT0_QPLLREFCLK_IN),
        //---------------------------- Power-Down Ports ----------------------------
        .RXPD_IN                        (GT2_RXPD_IN),
        .TXPD_IN                        (GT2_TXPD_IN),
        //------------------- RX Initialization and Reset Ports --------------------
        .RXUSERRDY_IN                   (GT2_RXUSERRDY_IN),
        //------------------------ RX Margin Analysis Ports ------------------------
        .EYESCANRESET_IN                (GT2_EYESCANRESET_IN),
        .EYESCANTRIGGER_IN              (GT2_EYESCANTRIGGER_IN),
        .EYESCANDATAERROR_OUT           (GT2_EYESCANDATAERROR_OUT),
        //----------------------- Receive Ports - CDR Ports ------------------------
        .RXCDRLOCK_OUT                  (GT2_RXCDRLOCK_OUT),
        //---------------- Receive Ports - FPGA RX Interface Ports -----------------
        .RXUSRCLK_IN                    (GT2_RXUSRCLK_IN),
        .RXUSRCLK2_IN                   (GT2_RXUSRCLK2_IN),
        //---------------- Receive Ports - FPGA RX interface Ports -----------------
        .RXDATA_OUT                     (GT2_RXDATA_OUT),
        //----------------- Receive Ports - Pattern Checker Ports ------------------
        .RXPRBSERR_OUT                  (GT2_RXPRBSERR_OUT),
        .RXPRBSSEL_IN                   (GT2_RXPRBSSEL_IN),
        //----------------- Receive Ports - Pattern Checker ports ------------------
        .RXPRBSCNTRESET_IN              (GT2_RXPRBSCNTRESET_IN),
        //---------------- Receive Ports - RX 8B/10B Decoder Ports -----------------
        .RXDISPERR_OUT                  (GT2_RXDISPERR_OUT),
        .RXNOTINTABLE_OUT               (GT2_RXNOTINTABLE_OUT),
        .RX8B10BEN_IN                   (GT2_RX8B10BEN_IN),
        //------------------------- Receive Ports - RX AFE -------------------------
        .GTXRXP_IN                      (GT2_GTXRXP_IN),
        //---------------------- Receive Ports - RX AFE Ports ----------------------
        .GTXRXN_IN                      (GT2_GTXRXN_IN),
        //----------------- Receive Ports - RX Buffer Bypass Ports -----------------
        .RXBUFRESET_IN                  (GT2_RXBUFRESET_IN),
        .RXBUFSTATUS_OUT                (GT2_RXBUFSTATUS_OUT),
        //------------ Receive Ports - RX Byte and Word Alignment Ports ------------
        .RXBYTEISALIGNED_OUT            (GT2_RXBYTEISALIGNED_OUT),
        .RXMCOMMAALIGNEN_IN             (GT2_RXMCOMMAALIGNEN_IN),
        .RXPCOMMAALIGNEN_IN             (GT2_RXPCOMMAALIGNEN_IN),
        .RXCOMMADET_OUT                 (GT2_RXCOMMADET_OUT),
        .RXELECIDLE_OUT                 (GT2_RXELECIDLE_OUT),
        //------------------- Receive Ports - RX Equalizer Ports -------------------
        .RXDFELPMRESET_IN               (GT2_RXDFELPMRESET_IN),
        //------------------- Receive Ports - RX Equilizer Ports -------------------
        .RXLPMHFHOLD_IN                 (GT2_RXLPMHFHOLD_IN),
        .RXLPMLFHOLD_IN                 (GT2_RXLPMLFHOLD_IN),
        .RXDFEAGCHOLD_IN                (GT2_RXDFEAGCHOLD_IN),
        .RXDFELFHOLD_IN                 (GT2_RXDFELFHOLD_IN),
        //------------- Receive Ports - RX Fabric Output Control Ports -------------
        .RXOUTCLK_OUT                   (GT2_RXOUTCLK_OUT),
        //----------- Receive Ports - RX Initialization and Reset Ports ------------
        .GTRXRESET_IN                   (GT2_GTRXRESET_IN),
        .RXPCSRESET_IN                  (GT2_RXPCSRESET_IN),
        .RXPMARESET_IN                  (GT2_RXPMARESET_IN),
        //---------------- Receive Ports - RX Margin Analysis ports ----------------
        .RXLPMEN_IN                     (GT2_RXLPMEN_IN),
        //----------------- Receive Ports - RX8B/10B Decoder Ports -----------------
        .RXCHARISK_OUT                  (GT2_RXCHARISK_OUT),
        //------------ Receive Ports -RX Initialization and Reset Ports ------------
        .RXRESETDONE_OUT                (GT2_RXRESETDONE_OUT),
        //---------------------- TX Configurable Driver Ports ----------------------
        .TXPOSTCURSOR_IN                (GT2_TXPOSTCURSOR_IN),
        .TXPRECURSOR_IN                 (GT2_TXPRECURSOR_IN),
        //------------------- TX Initialization and Reset Ports --------------------
        .GTTXRESET_IN                   (GT2_GTTXRESET_IN),
        .TXUSERRDY_IN                   (GT2_TXUSERRDY_IN),
        //-------------- Transmit Ports - 8b10b Encoder Control Ports --------------
        .TXCHARDISPMODE_IN              (GT2_TXCHARDISPMODE_IN),
        .TXCHARDISPVAL_IN               (GT2_TXCHARDISPVAL_IN),
        .TX8B10BEN_IN                   (GT2_TX8B10BEN_IN),
        //---------------- Transmit Ports - FPGA TX Interface Ports ----------------
        .TXUSRCLK_IN                    (GT2_TXUSRCLK_IN),
        .TXUSRCLK2_IN                   (GT2_TXUSRCLK2_IN),
        //------------------- Transmit Ports - PCI Express Ports -------------------
        .TXELECIDLE_IN                  (1'b0),
        //---------------- Transmit Ports - Pattern Generator Ports ----------------
        .TXPRBSFORCEERR_IN              (GT2_TXPRBSFORCEERR_IN),
 
        //-------------------- Transmit Ports - TX Buffer Ports --------------------
        .TXBUFSTATUS_OUT                (GT2_TXBUFSTATUS_OUT),
        //------------- Transmit Ports - TX Configurable Driver Ports --------------
        .TXDIFFCTRL_IN                  (GT2_TXDIFFCTRL_IN),
        .TXINHIBIT_IN                   (GT2_TXINHIBIT_IN),
        //---------------- Transmit Ports - TX Data Path interface -----------------
        .TXDATA_IN                      (GT2_TXDATA_IN),
        //-------------- Transmit Ports - TX Driver and OOB signaling --------------
        .GTXTXN_OUT                     (GT2_GTXTXN_OUT),
        .GTXTXP_OUT                     (GT2_GTXTXP_OUT),
        //--------- Transmit Ports - TX Fabric Clock Output Control Ports ----------
        .TXOUTCLK_OUT                   (GT2_TXOUTCLK_OUT),
        .TXOUTCLKFABRIC_OUT             (GT2_TXOUTCLKFABRIC_OUT),
        .TXOUTCLKPCS_OUT                (GT2_TXOUTCLKPCS_OUT),
        //------------------- Transmit Ports - TX Gearbox Ports --------------------
        .TXCHARISK_IN                   (GT2_TXCHARISK_IN),
        //----------- Transmit Ports - TX Initialization and Reset Ports -----------
        .TXPCSRESET_IN                  (GT2_TXPCSRESET_IN),
        .TXPMARESET_IN                  (GT2_TXPMARESET_IN),
        .TXRESETDONE_OUT                (GT2_TXRESETDONE_OUT),
        //---------------- Transmit Ports - pattern Generator Ports ----------------
        .TXPRBSSEL_IN                   (GT2_TXPRBSSEL_IN)

    );

    //_________________________________________________________________________
    //_________________________________________________________________________
    //GT3  (X0Y7)

    system_displayport_0_0_gt_7_series_wrapper_4_GT #
    (
        // Simulation attributes
        .GT_SIM_GTRESET_SPEEDUP   (WRAPPER_SIM_GTRESET_SPEEDUP),
        .SIM_VERSION              (SIM_VERSION),
        .RX_DFE_KL_CFG2_IN        (RX_DFE_KL_CFG2_IN),
        .PCS_RSVD_ATTR_IN         (48'h000000000000),
        .PMA_RSV_IN               (PMA_RSV_IN)
    )
    gt3_gt_7_series_wrapper_4_i
    (
        //------------------------------- CPLL Ports -------------------------------
        .CPLLFBCLKLOST_OUT              (GT3_CPLLFBCLKLOST_OUT),
        .CPLLLOCK_OUT                   (GT3_CPLLLOCK_OUT),
        .CPLLLOCKDETCLK_IN              (GT3_CPLLLOCKDETCLK_IN),
        .CPLLREFCLKLOST_OUT             (GT3_CPLLREFCLKLOST_OUT),
        .CPLLRESET_IN                   (GT3_CPLLRESET_IN),
        //------------------------ Channel - Clocking Ports ------------------------
        .GTREFCLK0_IN                   (GT3_GTREFCLK0_IN),
        .GTREFCLK1_IN                   (GT3_GTREFCLK1_IN),
        .GTREFCLKSEL_IN                 (GT3_GTREFCLKSEL_IN),
        //-------------------------- Channel - DRP Ports  --------------------------
        .DRPADDR_IN                     (GT3_DRPADDR_IN),
        .DRPCLK_IN                      (GT3_DRPCLK_IN),
        .DRPDI_IN                       (GT3_DRPDI_IN),
        .DRPDO_OUT                      (GT3_DRPDO_OUT),
        .DRPEN_IN                       (GT3_DRPEN_IN),
        .DRPRDY_OUT                     (GT3_DRPRDY_OUT),
        .DRPWE_IN                       (GT3_DRPWE_IN),
        .TXPOLARITY_IN                  (GT3_TXPOLARITY_IN),
        .RXPOLARITY_IN                  (GT3_RXPOLARITY_IN),
        .LOOPBACK_IN                    (GT3_LOOPBACK_IN),
        .DMONITOROUT_OUT                (GT3_DMONITOROUT_OUT),
        .RXLPMHFOVRDEN_IN               (GT3_RXLPMHFOVRDEN_IN),
        .RXCDRHOLD_IN                   (GT3_RXCDRHOLD_IN),
        //----------------------------- Clocking Ports -----------------------------
        .QPLLCLK_IN                     (GT0_QPLLCLK_IN),
        .QPLLREFCLK_IN                  (GT0_QPLLREFCLK_IN),
        //---------------------------- Power-Down Ports ----------------------------
        .RXPD_IN                        (GT3_RXPD_IN),
        .TXPD_IN                        (GT3_TXPD_IN),
        //------------------- RX Initialization and Reset Ports --------------------
        .RXUSERRDY_IN                   (GT3_RXUSERRDY_IN),
        //------------------------ RX Margin Analysis Ports ------------------------
        .EYESCANRESET_IN                (GT3_EYESCANRESET_IN),
        .EYESCANTRIGGER_IN              (GT3_EYESCANTRIGGER_IN),
        .EYESCANDATAERROR_OUT           (GT3_EYESCANDATAERROR_OUT),
        //----------------------- Receive Ports - CDR Ports ------------------------
        .RXCDRLOCK_OUT                  (GT3_RXCDRLOCK_OUT),
        //---------------- Receive Ports - FPGA RX Interface Ports -----------------
        .RXUSRCLK_IN                    (GT3_RXUSRCLK_IN),
        .RXUSRCLK2_IN                   (GT3_RXUSRCLK2_IN),
        //---------------- Receive Ports - FPGA RX interface Ports -----------------
        .RXDATA_OUT                     (GT3_RXDATA_OUT),
        //----------------- Receive Ports - Pattern Checker Ports ------------------
        .RXPRBSERR_OUT                  (GT3_RXPRBSERR_OUT),
        .RXPRBSSEL_IN                   (GT3_RXPRBSSEL_IN),
        //----------------- Receive Ports - Pattern Checker ports ------------------
        .RXPRBSCNTRESET_IN              (GT3_RXPRBSCNTRESET_IN),
        //---------------- Receive Ports - RX 8B/10B Decoder Ports -----------------
        .RXDISPERR_OUT                  (GT3_RXDISPERR_OUT),
        .RXNOTINTABLE_OUT               (GT3_RXNOTINTABLE_OUT),
        .RX8B10BEN_IN                   (GT3_RX8B10BEN_IN),
        //------------------------- Receive Ports - RX AFE -------------------------
        .GTXRXP_IN                      (GT3_GTXRXP_IN),
        //---------------------- Receive Ports - RX AFE Ports ----------------------
        .GTXRXN_IN                      (GT3_GTXRXN_IN),
        //----------------- Receive Ports - RX Buffer Bypass Ports -----------------
        .RXBUFRESET_IN                  (GT3_RXBUFRESET_IN),
        .RXBUFSTATUS_OUT                (GT3_RXBUFSTATUS_OUT),
        //------------ Receive Ports - RX Byte and Word Alignment Ports ------------
        .RXBYTEISALIGNED_OUT            (GT3_RXBYTEISALIGNED_OUT),
        .RXMCOMMAALIGNEN_IN             (GT3_RXMCOMMAALIGNEN_IN),
        .RXPCOMMAALIGNEN_IN             (GT3_RXPCOMMAALIGNEN_IN),
        .RXCOMMADET_OUT                 (GT3_RXCOMMADET_OUT),
        .RXELECIDLE_OUT                 (GT3_RXELECIDLE_OUT),
        //------------------- Receive Ports - RX Equalizer Ports -------------------
        .RXDFELPMRESET_IN               (GT3_RXDFELPMRESET_IN),
        //------------------- Receive Ports - RX Equilizer Ports -------------------
        .RXLPMHFHOLD_IN                 (GT3_RXLPMHFHOLD_IN),
        .RXLPMLFHOLD_IN                 (GT3_RXLPMLFHOLD_IN),
        .RXDFEAGCHOLD_IN                (GT3_RXDFEAGCHOLD_IN),
        .RXDFELFHOLD_IN                 (GT3_RXDFELFHOLD_IN),
        //------------- Receive Ports - RX Fabric Output Control Ports -------------
        .RXOUTCLK_OUT                   (GT3_RXOUTCLK_OUT),
        //----------- Receive Ports - RX Initialization and Reset Ports ------------
        .GTRXRESET_IN                   (GT3_GTRXRESET_IN),
        .RXPCSRESET_IN                  (GT3_RXPCSRESET_IN),
        .RXPMARESET_IN                  (GT3_RXPMARESET_IN),
        //---------------- Receive Ports - RX Margin Analysis ports ----------------
        .RXLPMEN_IN                     (GT3_RXLPMEN_IN),
        //----------------- Receive Ports - RX8B/10B Decoder Ports -----------------
        .RXCHARISK_OUT                  (GT3_RXCHARISK_OUT),
        //------------ Receive Ports -RX Initialization and Reset Ports ------------
        .RXRESETDONE_OUT                (GT3_RXRESETDONE_OUT),
        //---------------------- TX Configurable Driver Ports ----------------------
        .TXPOSTCURSOR_IN                (GT3_TXPOSTCURSOR_IN),
        .TXPRECURSOR_IN                 (GT3_TXPRECURSOR_IN),
        //------------------- TX Initialization and Reset Ports --------------------
        .GTTXRESET_IN                   (GT3_GTTXRESET_IN),
        .TXUSERRDY_IN                   (GT3_TXUSERRDY_IN),
        //-------------- Transmit Ports - 8b10b Encoder Control Ports --------------
        .TXCHARDISPMODE_IN              (GT3_TXCHARDISPMODE_IN),
        .TXCHARDISPVAL_IN               (GT3_TXCHARDISPVAL_IN),
        .TX8B10BEN_IN                   (GT3_TX8B10BEN_IN),
        //---------------- Transmit Ports - FPGA TX Interface Ports ----------------
        .TXUSRCLK_IN                    (GT3_TXUSRCLK_IN),
        .TXUSRCLK2_IN                   (GT3_TXUSRCLK2_IN),
        //------------------- Transmit Ports - PCI Express Ports -------------------
        .TXELECIDLE_IN                  (1'b0),
        //---------------- Transmit Ports - Pattern Generator Ports ----------------
        .TXPRBSFORCEERR_IN              (GT3_TXPRBSFORCEERR_IN),
 
        //-------------------- Transmit Ports - TX Buffer Ports --------------------
        .TXBUFSTATUS_OUT                (GT3_TXBUFSTATUS_OUT),
        //------------- Transmit Ports - TX Configurable Driver Ports --------------
        .TXDIFFCTRL_IN                  (GT3_TXDIFFCTRL_IN),
        .TXINHIBIT_IN                   (GT3_TXINHIBIT_IN),
        //---------------- Transmit Ports - TX Data Path interface -----------------
        .TXDATA_IN                      (GT3_TXDATA_IN),
        //-------------- Transmit Ports - TX Driver and OOB signaling --------------
        .GTXTXN_OUT                     (GT3_GTXTXN_OUT),
        .GTXTXP_OUT                     (GT3_GTXTXP_OUT),
        //--------- Transmit Ports - TX Fabric Clock Output Control Ports ----------
        .TXOUTCLK_OUT                   (GT3_TXOUTCLK_OUT),
        .TXOUTCLKFABRIC_OUT             (GT3_TXOUTCLKFABRIC_OUT),
        .TXOUTCLKPCS_OUT                (GT3_TXOUTCLKPCS_OUT),
        //------------------- Transmit Ports - TX Gearbox Ports --------------------
        .TXCHARISK_IN                   (GT3_TXCHARISK_IN),
        //----------- Transmit Ports - TX Initialization and Reset Ports -----------
        .TXPCSRESET_IN                  (GT3_TXPCSRESET_IN),
        .TXPMARESET_IN                  (GT3_TXPMARESET_IN),
        .TXRESETDONE_OUT                (GT3_TXRESETDONE_OUT),
        //---------------- Transmit Ports - pattern Generator Ports ----------------
        .TXPRBSSEL_IN                   (GT3_TXPRBSSEL_IN)

    );


endmodule

    
